### ISSUE TITLE
Code of Conduct needed

### ISSUE THREAD

**Issue by seanson** [pyslackers/community#1]
As an inclusive community it is important that we have a clear and open policy on the kind of community and behaviours we expect from ourselves.

There are some good sources in the community that can aid this, like:

-  the Python Diversity page: https://wiki.python.org/moin/DiversityInPython
- the django response guide https://www.djangoproject.com/conduct/enforcement-manual/
- the existing contributor covenant http://contributor-covenant.org

**Comment by joesanford** [comment]
Mind if I take a crack at this? I'm in the process of writing one for my job as well for compliance (I think that's why I do everything these days).

I'll get a rough draft together and PR it so we can iterate on it.

**Comment by mattrasband** [comment]
I think this is covered via https://pyslackers.com/terms/
