### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ovv** [pyslackers/community#15]
We should create a global `contributing.md` that can be used for all community repos.

Could be based on the [sirbot contributing guide](http://sir-bot-a-lot.readthedocs.io/en/latest/contributing.html)

**Comment by khdc-me** [comment]
Updated link to sir-bot-a-lot-2's [CONTRIBUTING.md](https://github.com/pyslackers/sir-bot-a-lot-2/blob/master/CONTRIBUTING.rst)

I was thinking of cleaning up and moving the text from 'how-we-git.md'  to this suggested file, but I'm looking at the doc I've linked to above... It's very well done. What's wrong w/ just using that? Except for the **Get Started** stuff that references sir-bot-a-lot-2, it def be applied to any other project.

**Comment by ovv** [comment]
Using that is fine, we just need to remove the `Get Started` part
