### ISSUE TITLE
Data binding over websockets in django channels

### ISSUE THREAD

**Issue by datasleek** [pyslackers/community#42]
Issue is as follows:

[Data Binding Issue](https://stackoverflow.com/questions/54944988/how-to-do-websocket-binding-in-a-django-model-that-has-a-field-of-foreignkey-typ)

I cannot find any help on this issue.It would be a great help if someone would help me out.

**Comment by mattrasband** [comment]
Hi, we don’t really do support over issues (and this issue is unrelated to our community repo).

We’d love to have you [join the group](https://pyslackers.com/slack/) and ask in the `#django` channel, hoowever!
